/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var p=Object.defineProperty;var f=Object.getOwnPropertyDescriptor;var k=Object.getOwnPropertyNames;var b=Object.prototype.hasOwnProperty;var E=(o,n)=>{for(var t in n)p(o,t,{get:n[t],enumerable:!0})},S=(o,n,t,a)=>{if(n&&typeof n=="object"||typeof n=="function")for(let c of k(n))!b.call(o,c)&&c!==t&&p(o,c,{get:()=>n[c],enumerable:!(a=f(n,c))||a.enumerable});return o};var z=o=>S(p({},"__esModule",{value:!0}),o);var x={};E(x,{default:()=>d});module.exports=z(x);var e=require("obsidian"),G={accessToken:""},d=class extends e.Plugin{async onload(){await this.loadSettings(),this.addRibbonIcon("image","Upload to Gyazo",async()=>{await this.uploadToGyazo()}),this.addCommand({id:"upload-to-gyazo",name:"Upload to Gyazo",editorCallback:async(t,a)=>{await this.uploadToGyazo()}}),this.addSettingTab(new l(this.app,this))}onunload(){}async loadSettings(){this.settings=Object.assign({},G,await this.loadData())}async saveSettings(){await this.saveData(this.settings)}async uploadToGyazo(){if(!this.settings.accessToken){new e.Notice("Please set your Gyazo access token in the settings.");return}try{let a=(await navigator.clipboard.read()).find(i=>i.types.includes("image/png")||i.types.includes("image/jpeg"));if(!a){new e.Notice("No image found in clipboard.");return}let w=await(await a.getType("image/png")).arrayBuffer(),r="----formdata-obsidian-"+Math.random().toString(36),s=[];s.push(new TextEncoder().encode(`--${r}\r
`)),s.push(new TextEncoder().encode(`Content-Disposition: form-data; name="access_token"\r
\r
`)),s.push(new TextEncoder().encode(`${this.settings.accessToken}\r
`)),s.push(new TextEncoder().encode(`--${r}\r
`)),s.push(new TextEncoder().encode(`Content-Disposition: form-data; name="imagedata"; filename="image.png"\r
`)),s.push(new TextEncoder().encode(`Content-Type: image/png\r
\r
`)),s.push(new Uint8Array(w)),s.push(new TextEncoder().encode(`\r
--${r}--\r
`));let T=s.reduce((i,g)=>i+g.length,0),u=new Uint8Array(T),h=0;for(let i of s)u.set(i,h),h+=i.length;let y=(await(0,e.requestUrl)({url:"https://upload.gyazo.com/api/upload",method:"POST",body:u.buffer,headers:{"Content-Type":`multipart/form-data; boundary=${r}`}})).json,m=this.app.workspace.getActiveViewOfType(e.MarkdownView);if(m){let i=m.editor,g=`![${y.image_id}](${y.url})`;i.replaceSelection(g),new e.Notice("Image uploaded successfully!")}}catch(t){new e.Notice("Failed to upload image: "+t.message)}}},l=class extends e.PluginSettingTab{constructor(t,a){super(t,a);this.plugin=a}display(){let{containerEl:t}=this;t.empty(),new e.Setting(t).setName("Gyazo Access Token").setDesc("Enter your Gyazo access token").addText(a=>a.setPlaceholder("Enter your access token").setValue(this.plugin.settings.accessToken).onChange(async c=>{this.plugin.settings.accessToken=c,await this.plugin.saveSettings()}))}};
